package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCSET.
 */
public class Accset implements java.io.Serializable {

    private Long AccsetID;
    private String AccsetCode;
    private String AccsetName;

    public Accset() {
    }

    public Accset(Long AccsetID, String AccsetCode, String AccsetName) {
        this.AccsetID = AccsetID;
        this.AccsetCode = AccsetCode;
        this.AccsetName = AccsetName;
    }

    public Long getAccsetID() {
        return AccsetID;
    }

    public void setAccsetID(Long AccsetID) {
        this.AccsetID = AccsetID;
    }

    public String getAccsetCode() {
        return AccsetCode;
    }

    public void setAccsetCode(String AccsetCode) {
        this.AccsetCode = AccsetCode;
    }

    public String getAccsetName() {
        return AccsetName;
    }

    public void setAccsetName(String AccsetName) {
        this.AccsetName = AccsetName;
    }

}
