package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AREA.
 */
public class Area implements java.io.Serializable {

    private Long AreaID;
    private String AreaCode;
    private String AreaName;
    private String LCode;
    private Long ParentID;

    public Area() {
    }

    public Area(Long AreaID, String AreaCode, String AreaName, String LCode, Long ParentID) {
        this.AreaID = AreaID;
        this.AreaCode = AreaCode;
        this.AreaName = AreaName;
        this.LCode = LCode;
        this.ParentID = ParentID;
    }

    public Long getAreaID() {
        return AreaID;
    }

    public void setAreaID(Long AreaID) {
        this.AreaID = AreaID;
    }

    public String getAreaCode() {
        return AreaCode;
    }

    public void setAreaCode(String AreaCode) {
        this.AreaCode = AreaCode;
    }

    public String getAreaName() {
        return AreaName;
    }

    public void setAreaName(String AreaName) {
        this.AreaName = AreaName;
    }

    public String getLCode() {
        return LCode;
    }

    public void setLCode(String LCode) {
        this.LCode = LCode;
    }

    public Long getParentID() {
        return ParentID;
    }

    public void setParentID(Long ParentID) {
        this.ParentID = ParentID;
    }

}
