package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEPARTMENT.
 */
public class Department implements java.io.Serializable {

    private Long DepartmentID;
    private String DepartmentCode;
    private String DepartmentName;
    private Boolean Close;

    public Department() {
    }

    public Department(Long DepartmentID, String DepartmentCode, String DepartmentName, Boolean Close) {
        this.DepartmentID = DepartmentID;
        this.DepartmentCode = DepartmentCode;
        this.DepartmentName = DepartmentName;
        this.Close = Close;
    }

    public Long getDepartmentID() {
        return DepartmentID;
    }

    public void setDepartmentID(Long DepartmentID) {
        this.DepartmentID = DepartmentID;
    }

    public String getDepartmentCode() {
        return DepartmentCode;
    }

    public void setDepartmentCode(String DepartmentCode) {
        this.DepartmentCode = DepartmentCode;
    }

    public String getDepartmentName() {
        return DepartmentName;
    }

    public void setDepartmentName(String DepartmentName) {
        this.DepartmentName = DepartmentName;
    }

    public Boolean getClose() {
        return Close;
    }

    public void setClose(Boolean Close) {
        this.Close = Close;
    }

}
