package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DETAIL1_DATA.
 */
public class Detail1Data implements java.io.Serializable {

    private Long BillID;
    private Integer ItemNO;
    private Double APrice;
    private Double Amount;
    private Long BReferID;
    private Double Disc;
    private Double DiscAmt;
    private Long GoodsID;
    private Double GoodsAmt;
    private Integer IsLargess;
    private Double OrigPrice;
    private Double OrigTaxPrice;
    private Double Quantity;
    private Long ReferBillCode;
    private Long ReferBillID;
    private Integer ReferBillType;
    private Integer ReferItemNo;
    private Long StoreID;
    private Double TaxAmt;
    private Double TaxPrice;
    private Double TaxRate;
    private Long UnitID;
    private Double UnitPrice;
    private Double UnitQuantity;
    private Double UnitRate;
    private String UserDef1;
    private String UserDef2;
    private String UserDef3;
    private String UserDef4;
    private String UserDef5;
    private String UserDef6;
    private String UserDef7;
    private String UserDef8;
    private String UserDef9;
    private String UserDef10;

    public Detail1Data() {
    }

    public Detail1Data(Long BillID, Integer ItemNO, Double APrice, Double Amount, Long BReferID, Double Disc, Double DiscAmt, Long GoodsID, Double GoodsAmt, Integer IsLargess, Double OrigPrice, Double OrigTaxPrice, Double Quantity, Long ReferBillCode, Long ReferBillID, Integer ReferBillType, Integer ReferItemNo, Long StoreID, Double TaxAmt, Double TaxPrice, Double TaxRate, Long UnitID, Double UnitPrice, Double UnitQuantity, Double UnitRate, String UserDef1, String UserDef2, String UserDef3, String UserDef4, String UserDef5, String UserDef6, String UserDef7, String UserDef8, String UserDef9, String UserDef10) {
        this.BillID = BillID;
        this.ItemNO = ItemNO;
        this.APrice = APrice;
        this.Amount = Amount;
        this.BReferID = BReferID;
        this.Disc = Disc;
        this.DiscAmt = DiscAmt;
        this.GoodsID = GoodsID;
        this.GoodsAmt = GoodsAmt;
        this.IsLargess = IsLargess;
        this.OrigPrice = OrigPrice;
        this.OrigTaxPrice = OrigTaxPrice;
        this.Quantity = Quantity;
        this.ReferBillCode = ReferBillCode;
        this.ReferBillID = ReferBillID;
        this.ReferBillType = ReferBillType;
        this.ReferItemNo = ReferItemNo;
        this.StoreID = StoreID;
        this.TaxAmt = TaxAmt;
        this.TaxPrice = TaxPrice;
        this.TaxRate = TaxRate;
        this.UnitID = UnitID;
        this.UnitPrice = UnitPrice;
        this.UnitQuantity = UnitQuantity;
        this.UnitRate = UnitRate;
        this.UserDef1 = UserDef1;
        this.UserDef2 = UserDef2;
        this.UserDef3 = UserDef3;
        this.UserDef4 = UserDef4;
        this.UserDef5 = UserDef5;
        this.UserDef6 = UserDef6;
        this.UserDef7 = UserDef7;
        this.UserDef8 = UserDef8;
        this.UserDef9 = UserDef9;
        this.UserDef10 = UserDef10;
    }

    public Long getBillID() {
        return BillID;
    }

    public void setBillID(Long BillID) {
        this.BillID = BillID;
    }

    public Integer getItemNO() {
        return ItemNO;
    }

    public void setItemNO(Integer ItemNO) {
        this.ItemNO = ItemNO;
    }

    public Double getAPrice() {
        return APrice;
    }

    public void setAPrice(Double APrice) {
        this.APrice = APrice;
    }

    public Double getAmount() {
        return Amount;
    }

    public void setAmount(Double Amount) {
        this.Amount = Amount;
    }

    public Long getBReferID() {
        return BReferID;
    }

    public void setBReferID(Long BReferID) {
        this.BReferID = BReferID;
    }

    public Double getDisc() {
        return Disc;
    }

    public void setDisc(Double Disc) {
        this.Disc = Disc;
    }

    public Double getDiscAmt() {
        return DiscAmt;
    }

    public void setDiscAmt(Double DiscAmt) {
        this.DiscAmt = DiscAmt;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public Double getGoodsAmt() {
        return GoodsAmt;
    }

    public void setGoodsAmt(Double GoodsAmt) {
        this.GoodsAmt = GoodsAmt;
    }

    public Integer getIsLargess() {
        return IsLargess;
    }

    public void setIsLargess(Integer IsLargess) {
        this.IsLargess = IsLargess;
    }

    public Double getOrigPrice() {
        return OrigPrice;
    }

    public void setOrigPrice(Double OrigPrice) {
        this.OrigPrice = OrigPrice;
    }

    public Double getOrigTaxPrice() {
        return OrigTaxPrice;
    }

    public void setOrigTaxPrice(Double OrigTaxPrice) {
        this.OrigTaxPrice = OrigTaxPrice;
    }

    public Double getQuantity() {
        return Quantity;
    }

    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    public Long getReferBillCode() {
        return ReferBillCode;
    }

    public void setReferBillCode(Long ReferBillCode) {
        this.ReferBillCode = ReferBillCode;
    }

    public Long getReferBillID() {
        return ReferBillID;
    }

    public void setReferBillID(Long ReferBillID) {
        this.ReferBillID = ReferBillID;
    }

    public Integer getReferBillType() {
        return ReferBillType;
    }

    public void setReferBillType(Integer ReferBillType) {
        this.ReferBillType = ReferBillType;
    }

    public Integer getReferItemNo() {
        return ReferItemNo;
    }

    public void setReferItemNo(Integer ReferItemNo) {
        this.ReferItemNo = ReferItemNo;
    }

    public Long getStoreID() {
        return StoreID;
    }

    public void setStoreID(Long StoreID) {
        this.StoreID = StoreID;
    }

    public Double getTaxAmt() {
        return TaxAmt;
    }

    public void setTaxAmt(Double TaxAmt) {
        this.TaxAmt = TaxAmt;
    }

    public Double getTaxPrice() {
        return TaxPrice;
    }

    public void setTaxPrice(Double TaxPrice) {
        this.TaxPrice = TaxPrice;
    }

    public Double getTaxRate() {
        return TaxRate;
    }

    public void setTaxRate(Double TaxRate) {
        this.TaxRate = TaxRate;
    }

    public Long getUnitID() {
        return UnitID;
    }

    public void setUnitID(Long UnitID) {
        this.UnitID = UnitID;
    }

    public Double getUnitPrice() {
        return UnitPrice;
    }

    public void setUnitPrice(Double UnitPrice) {
        this.UnitPrice = UnitPrice;
    }

    public Double getUnitQuantity() {
        return UnitQuantity;
    }

    public void setUnitQuantity(Double UnitQuantity) {
        this.UnitQuantity = UnitQuantity;
    }

    public Double getUnitRate() {
        return UnitRate;
    }

    public void setUnitRate(Double UnitRate) {
        this.UnitRate = UnitRate;
    }

    public String getUserDef1() {
        return UserDef1;
    }

    public void setUserDef1(String UserDef1) {
        this.UserDef1 = UserDef1;
    }

    public String getUserDef2() {
        return UserDef2;
    }

    public void setUserDef2(String UserDef2) {
        this.UserDef2 = UserDef2;
    }

    public String getUserDef3() {
        return UserDef3;
    }

    public void setUserDef3(String UserDef3) {
        this.UserDef3 = UserDef3;
    }

    public String getUserDef4() {
        return UserDef4;
    }

    public void setUserDef4(String UserDef4) {
        this.UserDef4 = UserDef4;
    }

    public String getUserDef5() {
        return UserDef5;
    }

    public void setUserDef5(String UserDef5) {
        this.UserDef5 = UserDef5;
    }

    public String getUserDef6() {
        return UserDef6;
    }

    public void setUserDef6(String UserDef6) {
        this.UserDef6 = UserDef6;
    }

    public String getUserDef7() {
        return UserDef7;
    }

    public void setUserDef7(String UserDef7) {
        this.UserDef7 = UserDef7;
    }

    public String getUserDef8() {
        return UserDef8;
    }

    public void setUserDef8(String UserDef8) {
        this.UserDef8 = UserDef8;
    }

    public String getUserDef9() {
        return UserDef9;
    }

    public void setUserDef9(String UserDef9) {
        this.UserDef9 = UserDef9;
    }

    public String getUserDef10() {
        return UserDef10;
    }

    public void setUserDef10(String UserDef10) {
        this.UserDef10 = UserDef10;
    }

}
