package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EMPLOYEE.
 */
public class Employee implements java.io.Serializable {

    private Long EmpID;
    private String EmpCode;
    private String EmpName;
    private Long DepartmentID;
    private String Sex;
    private Boolean Close;

    public Employee() {
    }

    public Employee(Long EmpID, String EmpCode, String EmpName, Long DepartmentID, String Sex, Boolean Close) {
        this.EmpID = EmpID;
        this.EmpCode = EmpCode;
        this.EmpName = EmpName;
        this.DepartmentID = DepartmentID;
        this.Sex = Sex;
        this.Close = Close;
    }

    public Long getEmpID() {
        return EmpID;
    }

    public void setEmpID(Long EmpID) {
        this.EmpID = EmpID;
    }

    public String getEmpCode() {
        return EmpCode;
    }

    public void setEmpCode(String EmpCode) {
        this.EmpCode = EmpCode;
    }

    public String getEmpName() {
        return EmpName;
    }

    public void setEmpName(String EmpName) {
        this.EmpName = EmpName;
    }

    public Long getDepartmentID() {
        return DepartmentID;
    }

    public void setDepartmentID(Long DepartmentID) {
        this.DepartmentID = DepartmentID;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    public Boolean getClose() {
        return Close;
    }

    public void setClose(Boolean Close) {
        this.Close = Close;
    }

}
