package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GOODS.
 */
public class Goods implements java.io.Serializable {

    private Long GoodsID;
    private String GoodsCode;
    private String GoodsName;
    private String ShortName;
    private String Specs;
    private Long GDTypeID;
    private String GDUserDef1;
    private String GDUserDef2;
    private String GDUserDef3;
    private String GDUserDef4;
    private String GDUserDef5;
    private String GDUserDef6;
    private String GDUserDef7;
    private String GDUserDef8;
    private String GDUserDef9;
    private String GDUserDef10;

    public Goods() {
    }

    public Goods(Long GoodsID, String GoodsCode, String GoodsName, String ShortName, String Specs, Long GDTypeID, String GDUserDef1, String GDUserDef2, String GDUserDef3, String GDUserDef4, String GDUserDef5, String GDUserDef6, String GDUserDef7, String GDUserDef8, String GDUserDef9, String GDUserDef10) {
        this.GoodsID = GoodsID;
        this.GoodsCode = GoodsCode;
        this.GoodsName = GoodsName;
        this.ShortName = ShortName;
        this.Specs = Specs;
        this.GDTypeID = GDTypeID;
        this.GDUserDef1 = GDUserDef1;
        this.GDUserDef2 = GDUserDef2;
        this.GDUserDef3 = GDUserDef3;
        this.GDUserDef4 = GDUserDef4;
        this.GDUserDef5 = GDUserDef5;
        this.GDUserDef6 = GDUserDef6;
        this.GDUserDef7 = GDUserDef7;
        this.GDUserDef8 = GDUserDef8;
        this.GDUserDef9 = GDUserDef9;
        this.GDUserDef10 = GDUserDef10;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public String getGoodsCode() {
        return GoodsCode;
    }

    public void setGoodsCode(String GoodsCode) {
        this.GoodsCode = GoodsCode;
    }

    public String getGoodsName() {
        return GoodsName;
    }

    public void setGoodsName(String GoodsName) {
        this.GoodsName = GoodsName;
    }

    public String getShortName() {
        return ShortName;
    }

    public void setShortName(String ShortName) {
        this.ShortName = ShortName;
    }

    public String getSpecs() {
        return Specs;
    }

    public void setSpecs(String Specs) {
        this.Specs = Specs;
    }

    public Long getGDTypeID() {
        return GDTypeID;
    }

    public void setGDTypeID(Long GDTypeID) {
        this.GDTypeID = GDTypeID;
    }

    public String getGDUserDef1() {
        return GDUserDef1;
    }

    public void setGDUserDef1(String GDUserDef1) {
        this.GDUserDef1 = GDUserDef1;
    }

    public String getGDUserDef2() {
        return GDUserDef2;
    }

    public void setGDUserDef2(String GDUserDef2) {
        this.GDUserDef2 = GDUserDef2;
    }

    public String getGDUserDef3() {
        return GDUserDef3;
    }

    public void setGDUserDef3(String GDUserDef3) {
        this.GDUserDef3 = GDUserDef3;
    }

    public String getGDUserDef4() {
        return GDUserDef4;
    }

    public void setGDUserDef4(String GDUserDef4) {
        this.GDUserDef4 = GDUserDef4;
    }

    public String getGDUserDef5() {
        return GDUserDef5;
    }

    public void setGDUserDef5(String GDUserDef5) {
        this.GDUserDef5 = GDUserDef5;
    }

    public String getGDUserDef6() {
        return GDUserDef6;
    }

    public void setGDUserDef6(String GDUserDef6) {
        this.GDUserDef6 = GDUserDef6;
    }

    public String getGDUserDef7() {
        return GDUserDef7;
    }

    public void setGDUserDef7(String GDUserDef7) {
        this.GDUserDef7 = GDUserDef7;
    }

    public String getGDUserDef8() {
        return GDUserDef8;
    }

    public void setGDUserDef8(String GDUserDef8) {
        this.GDUserDef8 = GDUserDef8;
    }

    public String getGDUserDef9() {
        return GDUserDef9;
    }

    public void setGDUserDef9(String GDUserDef9) {
        this.GDUserDef9 = GDUserDef9;
    }

    public String getGDUserDef10() {
        return GDUserDef10;
    }

    public void setGDUserDef10(String GDUserDef10) {
        this.GDUserDef10 = GDUserDef10;
    }

}
