package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GOODS_PICTURE.
 */
public class GoodsPicture implements java.io.Serializable {

    private Long ID;
    private String Picture;
    private String PictureExt;

    public GoodsPicture() {
    }

    public GoodsPicture(Long ID, String Picture, String PictureExt) {
        this.ID = ID;
        this.Picture = Picture;
        this.PictureExt = PictureExt;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getPicture() {
        return Picture;
    }

    public void setPicture(String Picture) {
        this.Picture = Picture;
    }

    public String getPictureExt() {
        return PictureExt;
    }

    public void setPictureExt(String PictureExt) {
        this.PictureExt = PictureExt;
    }

}
