package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ON_HAND.
 */
public class OnHand implements java.io.Serializable {

    private Long StoreID;
    private Long GoodsID;
    private Double Quantity;
    private Double RealQty;

    public OnHand() {
    }

    public OnHand(Long StoreID, Long GoodsID, Double Quantity, Double RealQty) {
        this.StoreID = StoreID;
        this.GoodsID = GoodsID;
        this.Quantity = Quantity;
        this.RealQty = RealQty;
    }

    public Long getStoreID() {
        return StoreID;
    }

    public void setStoreID(Long StoreID) {
        this.StoreID = StoreID;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public Double getQuantity() {
        return Quantity;
    }

    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    public Double getRealQty() {
        return RealQty;
    }

    public void setRealQty(Double RealQty) {
        this.RealQty = RealQty;
    }

}
