package com.twisty.superclient.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table SALES_ORDER_DETAIL1_DATA.
 */
public class SalesOrderDetail1DataDao extends AbstractDao<SalesOrderDetail1Data, Long> {

    public static final String TABLENAME = "SALES_ORDER_DETAIL1_DATA";
    private Query<SalesOrderDetail1Data> salesOrderMasterData_SalesOrderDetail1DataListQuery;
    ;

    public SalesOrderDetail1DataDao(DaoConfig config) {
        super(config);
    }

    public SalesOrderDetail1DataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'SALES_ORDER_DETAIL1_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MASTER_ID' INTEGER," + // 1: MasterID
                "'BILL_ID' INTEGER," + // 2: BillID
                "'ITEM_NO' INTEGER," + // 3: ItemNo
                "'APRICE' REAL," + // 4: APrice
                "'AMOUNT' REAL," + // 5: Amount
                "'BAR_CODE' TEXT," + // 6: BarCode
                "'CHARGE_DATE' TEXT," + // 7: ChargeDate
                "'CLOSED' INTEGER," + // 8: Closed
                "'DISC' REAL," + // 9: Disc
                "'GUSER_DEF1' TEXT," + // 10: GUserDef1
                "'GUSER_DEF2' TEXT," + // 11: GUserDef2
                "'GUSER_DEF3' TEXT," + // 12: GUserDef3
                "'GUSER_DEF4' TEXT," + // 13: GUserDef4
                "'GUSER_DEF5' TEXT," + // 14: GUserDef5
                "'GOODS_AMT' REAL," + // 15: GoodsAmt
                "'GOODS_CODE' TEXT," + // 16: GoodsCode
                "'GOODS_ID' INTEGER," + // 17: GoodsID
                "'GOODS_NAME' TEXT," + // 18: GoodsName
                "'IS_LARGESS' INTEGER," + // 19: IsLargess
                "'ORIG_PRICE' REAL," + // 20: OrigPrice
                "'ORIG_TAX_PRICE' REAL," + // 21: OrigTaxPrice
                "'TAX_PRICE' REAL," + // 22: TaxPrice
                "'PRICE' REAL," + // 23: Price
                "'QUANTITY' REAL," + // 24: Quantity
                "'REFER_BILL_CODE' TEXT," + // 25: ReferBillCode
                "'REFER_BILL_ID' INTEGER," + // 26: ReferBillID
                "'REFER_BILL_TYPE' TEXT," + // 27: ReferBillType
                "'REFER_COUNT' INTEGER," + // 28: ReferCount
                "'REFER_ITEM_NO' INTEGER," + // 29: ReferItemNo
                "'REFER_QTY' REAL," + // 30: ReferQty
                "'REMARK' TEXT," + // 31: Remark
                "'SHORT_NAME' TEXT," + // 32: ShortName
                "'SPECS' TEXT," + // 33: Specs
                "'STORE_ID' INTEGER," + // 34: StoreID
                "'TAX_AMT' REAL," + // 35: TaxAmt
                "'TAX_RATE' REAL," + // 36: TaxRate
                "'UNIT_ID' INTEGER," + // 37: UnitID
                "'UNIT_NAME' TEXT," + // 38: UnitName
                "'UNIT_PRICE' REAL," + // 39: UnitPrice
                "'UNIT_QUANTITY' REAL," + // 40: UnitQuantity
                "'UNIT_RATE' REAL," + // 41: UnitRate
                "'USER_DEF1' TEXT," + // 42: UserDef1
                "'USER_DEF2' TEXT," + // 43: UserDef2
                "'USER_DEF3' TEXT," + // 44: UserDef3
                "'USER_DEF4' TEXT," + // 45: UserDef4
                "'USER_DEF5' TEXT);"); // 46: UserDef5
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_SALES_ORDER_DETAIL1_DATA__id ON SALES_ORDER_DETAIL1_DATA" +
                " (_id);");
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SALES_ORDER_DETAIL1_DATA'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, SalesOrderDetail1Data entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Long MasterID = entity.getMasterID();
        if (MasterID != null) {
            stmt.bindLong(2, MasterID);
        }

        Long BillID = entity.getBillID();
        if (BillID != null) {
            stmt.bindLong(3, BillID);
        }

        Integer ItemNo = entity.getItemNo();
        if (ItemNo != null) {
            stmt.bindLong(4, ItemNo);
        }

        Double APrice = entity.getAPrice();
        if (APrice != null) {
            stmt.bindDouble(5, APrice);
        }

        Double Amount = entity.getAmount();
        if (Amount != null) {
            stmt.bindDouble(6, Amount);
        }

        String BarCode = entity.getBarCode();
        if (BarCode != null) {
            stmt.bindString(7, BarCode);
        }

        String ChargeDate = entity.getChargeDate();
        if (ChargeDate != null) {
            stmt.bindString(8, ChargeDate);
        }

        Integer Closed = entity.getClosed();
        if (Closed != null) {
            stmt.bindLong(9, Closed);
        }

        Double Disc = entity.getDisc();
        if (Disc != null) {
            stmt.bindDouble(10, Disc);
        }

        String GUserDef1 = entity.getGUserDef1();
        if (GUserDef1 != null) {
            stmt.bindString(11, GUserDef1);
        }

        String GUserDef2 = entity.getGUserDef2();
        if (GUserDef2 != null) {
            stmt.bindString(12, GUserDef2);
        }

        String GUserDef3 = entity.getGUserDef3();
        if (GUserDef3 != null) {
            stmt.bindString(13, GUserDef3);
        }

        String GUserDef4 = entity.getGUserDef4();
        if (GUserDef4 != null) {
            stmt.bindString(14, GUserDef4);
        }

        String GUserDef5 = entity.getGUserDef5();
        if (GUserDef5 != null) {
            stmt.bindString(15, GUserDef5);
        }

        Double GoodsAmt = entity.getGoodsAmt();
        if (GoodsAmt != null) {
            stmt.bindDouble(16, GoodsAmt);
        }

        String GoodsCode = entity.getGoodsCode();
        if (GoodsCode != null) {
            stmt.bindString(17, GoodsCode);
        }

        Long GoodsID = entity.getGoodsID();
        if (GoodsID != null) {
            stmt.bindLong(18, GoodsID);
        }

        String GoodsName = entity.getGoodsName();
        if (GoodsName != null) {
            stmt.bindString(19, GoodsName);
        }

        Integer IsLargess = entity.getIsLargess();
        if (IsLargess != null) {
            stmt.bindLong(20, IsLargess);
        }

        Double OrigPrice = entity.getOrigPrice();
        if (OrigPrice != null) {
            stmt.bindDouble(21, OrigPrice);
        }

        Double OrigTaxPrice = entity.getOrigTaxPrice();
        if (OrigTaxPrice != null) {
            stmt.bindDouble(22, OrigTaxPrice);
        }

        Double TaxPrice = entity.getTaxPrice();
        if (TaxPrice != null) {
            stmt.bindDouble(23, TaxPrice);
        }

        Double Price = entity.getPrice();
        if (Price != null) {
            stmt.bindDouble(24, Price);
        }

        Double Quantity = entity.getQuantity();
        if (Quantity != null) {
            stmt.bindDouble(25, Quantity);
        }

        String ReferBillCode = entity.getReferBillCode();
        if (ReferBillCode != null) {
            stmt.bindString(26, ReferBillCode);
        }

        Long ReferBillID = entity.getReferBillID();
        if (ReferBillID != null) {
            stmt.bindLong(27, ReferBillID);
        }

        String ReferBillType = entity.getReferBillType();
        if (ReferBillType != null) {
            stmt.bindString(28, ReferBillType);
        }

        Integer ReferCount = entity.getReferCount();
        if (ReferCount != null) {
            stmt.bindLong(29, ReferCount);
        }

        Integer ReferItemNo = entity.getReferItemNo();
        if (ReferItemNo != null) {
            stmt.bindLong(30, ReferItemNo);
        }

        Double ReferQty = entity.getReferQty();
        if (ReferQty != null) {
            stmt.bindDouble(31, ReferQty);
        }

        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(32, Remark);
        }

        String ShortName = entity.getShortName();
        if (ShortName != null) {
            stmt.bindString(33, ShortName);
        }

        String Specs = entity.getSpecs();
        if (Specs != null) {
            stmt.bindString(34, Specs);
        }

        Long StoreID = entity.getStoreID();
        if (StoreID != null) {
            stmt.bindLong(35, StoreID);
        }

        Double TaxAmt = entity.getTaxAmt();
        if (TaxAmt != null) {
            stmt.bindDouble(36, TaxAmt);
        }

        Double TaxRate = entity.getTaxRate();
        if (TaxRate != null) {
            stmt.bindDouble(37, TaxRate);
        }

        Long UnitID = entity.getUnitID();
        if (UnitID != null) {
            stmt.bindLong(38, UnitID);
        }

        String UnitName = entity.getUnitName();
        if (UnitName != null) {
            stmt.bindString(39, UnitName);
        }

        Double UnitPrice = entity.getUnitPrice();
        if (UnitPrice != null) {
            stmt.bindDouble(40, UnitPrice);
        }

        Double UnitQuantity = entity.getUnitQuantity();
        if (UnitQuantity != null) {
            stmt.bindDouble(41, UnitQuantity);
        }

        Double UnitRate = entity.getUnitRate();
        if (UnitRate != null) {
            stmt.bindDouble(42, UnitRate);
        }

        String UserDef1 = entity.getUserDef1();
        if (UserDef1 != null) {
            stmt.bindString(43, UserDef1);
        }

        String UserDef2 = entity.getUserDef2();
        if (UserDef2 != null) {
            stmt.bindString(44, UserDef2);
        }

        String UserDef3 = entity.getUserDef3();
        if (UserDef3 != null) {
            stmt.bindString(45, UserDef3);
        }

        String UserDef4 = entity.getUserDef4();
        if (UserDef4 != null) {
            stmt.bindString(46, UserDef4);
        }

        String UserDef5 = entity.getUserDef5();
        if (UserDef5 != null) {
            stmt.bindString(47, UserDef5);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public SalesOrderDetail1Data readEntity(Cursor cursor, int offset) {
        SalesOrderDetail1Data entity = new SalesOrderDetail1Data( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // MasterID
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // BillID
                cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // ItemNo
                cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // APrice
                cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5), // Amount
                cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // BarCode
                cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ChargeDate
                cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // Closed
                cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9), // Disc
                cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // GUserDef1
                cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // GUserDef2
                cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // GUserDef3
                cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // GUserDef4
                cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // GUserDef5
                cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15), // GoodsAmt
                cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // GoodsCode
                cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17), // GoodsID
                cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // GoodsName
                cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // IsLargess
                cursor.isNull(offset + 20) ? null : cursor.getDouble(offset + 20), // OrigPrice
                cursor.isNull(offset + 21) ? null : cursor.getDouble(offset + 21), // OrigTaxPrice
                cursor.isNull(offset + 22) ? null : cursor.getDouble(offset + 22), // TaxPrice
                cursor.isNull(offset + 23) ? null : cursor.getDouble(offset + 23), // Price
                cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24), // Quantity
                cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // ReferBillCode
                cursor.isNull(offset + 26) ? null : cursor.getLong(offset + 26), // ReferBillID
                cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // ReferBillType
                cursor.isNull(offset + 28) ? null : cursor.getInt(offset + 28), // ReferCount
                cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29), // ReferItemNo
                cursor.isNull(offset + 30) ? null : cursor.getDouble(offset + 30), // ReferQty
                cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // Remark
                cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // ShortName
                cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // Specs
                cursor.isNull(offset + 34) ? null : cursor.getLong(offset + 34), // StoreID
                cursor.isNull(offset + 35) ? null : cursor.getDouble(offset + 35), // TaxAmt
                cursor.isNull(offset + 36) ? null : cursor.getDouble(offset + 36), // TaxRate
                cursor.isNull(offset + 37) ? null : cursor.getLong(offset + 37), // UnitID
                cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // UnitName
                cursor.isNull(offset + 39) ? null : cursor.getDouble(offset + 39), // UnitPrice
                cursor.isNull(offset + 40) ? null : cursor.getDouble(offset + 40), // UnitQuantity
                cursor.isNull(offset + 41) ? null : cursor.getDouble(offset + 41), // UnitRate
                cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // UserDef1
                cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // UserDef2
                cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // UserDef3
                cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // UserDef4
                cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46) // UserDef5
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, SalesOrderDetail1Data entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMasterID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBillID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setItemNo(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAPrice(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setAmount(cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5));
        entity.setBarCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setChargeDate(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setClosed(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setDisc(cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9));
        entity.setGUserDef1(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setGUserDef2(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setGUserDef3(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGUserDef4(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setGUserDef5(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setGoodsAmt(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
        entity.setGoodsCode(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setGoodsID(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
        entity.setGoodsName(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setIsLargess(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setOrigPrice(cursor.isNull(offset + 20) ? null : cursor.getDouble(offset + 20));
        entity.setOrigTaxPrice(cursor.isNull(offset + 21) ? null : cursor.getDouble(offset + 21));
        entity.setTaxPrice(cursor.isNull(offset + 22) ? null : cursor.getDouble(offset + 22));
        entity.setPrice(cursor.isNull(offset + 23) ? null : cursor.getDouble(offset + 23));
        entity.setQuantity(cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24));
        entity.setReferBillCode(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setReferBillID(cursor.isNull(offset + 26) ? null : cursor.getLong(offset + 26));
        entity.setReferBillType(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setReferCount(cursor.isNull(offset + 28) ? null : cursor.getInt(offset + 28));
        entity.setReferItemNo(cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29));
        entity.setReferQty(cursor.isNull(offset + 30) ? null : cursor.getDouble(offset + 30));
        entity.setRemark(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setShortName(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setSpecs(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setStoreID(cursor.isNull(offset + 34) ? null : cursor.getLong(offset + 34));
        entity.setTaxAmt(cursor.isNull(offset + 35) ? null : cursor.getDouble(offset + 35));
        entity.setTaxRate(cursor.isNull(offset + 36) ? null : cursor.getDouble(offset + 36));
        entity.setUnitID(cursor.isNull(offset + 37) ? null : cursor.getLong(offset + 37));
        entity.setUnitName(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setUnitPrice(cursor.isNull(offset + 39) ? null : cursor.getDouble(offset + 39));
        entity.setUnitQuantity(cursor.isNull(offset + 40) ? null : cursor.getDouble(offset + 40));
        entity.setUnitRate(cursor.isNull(offset + 41) ? null : cursor.getDouble(offset + 41));
        entity.setUserDef1(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setUserDef2(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setUserDef3(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setUserDef4(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setUserDef5(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(SalesOrderDetail1Data entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(SalesOrderDetail1Data entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Internal query to resolve the "salesOrderDetail1DataList" to-many relationship of SalesOrderMasterData.
     */
    public List<SalesOrderDetail1Data> _querySalesOrderMasterData_SalesOrderDetail1DataList(Long MasterID) {
        synchronized (this) {
            if (salesOrderMasterData_SalesOrderDetail1DataListQuery == null) {
                QueryBuilder<SalesOrderDetail1Data> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MasterID.eq(null));
                salesOrderMasterData_SalesOrderDetail1DataListQuery = queryBuilder.build();
            }
        }
        Query<SalesOrderDetail1Data> query = salesOrderMasterData_SalesOrderDetail1DataListQuery.forCurrentThread();
        query.setParameter(0, MasterID);
        return query.list();
    }

    /**
     * Properties of entity SalesOrderDetail1Data.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MasterID = new Property(1, Long.class, "MasterID", false, "MASTER_ID");
        public final static Property BillID = new Property(2, Long.class, "BillID", false, "BILL_ID");
        public final static Property ItemNo = new Property(3, Integer.class, "ItemNo", false, "ITEM_NO");
        public final static Property APrice = new Property(4, Double.class, "APrice", false, "APRICE");
        public final static Property Amount = new Property(5, Double.class, "Amount", false, "AMOUNT");
        public final static Property BarCode = new Property(6, String.class, "BarCode", false, "BAR_CODE");
        public final static Property ChargeDate = new Property(7, String.class, "ChargeDate", false, "CHARGE_DATE");
        public final static Property Closed = new Property(8, Integer.class, "Closed", false, "CLOSED");
        public final static Property Disc = new Property(9, Double.class, "Disc", false, "DISC");
        public final static Property GUserDef1 = new Property(10, String.class, "GUserDef1", false, "GUSER_DEF1");
        public final static Property GUserDef2 = new Property(11, String.class, "GUserDef2", false, "GUSER_DEF2");
        public final static Property GUserDef3 = new Property(12, String.class, "GUserDef3", false, "GUSER_DEF3");
        public final static Property GUserDef4 = new Property(13, String.class, "GUserDef4", false, "GUSER_DEF4");
        public final static Property GUserDef5 = new Property(14, String.class, "GUserDef5", false, "GUSER_DEF5");
        public final static Property GoodsAmt = new Property(15, Double.class, "GoodsAmt", false, "GOODS_AMT");
        public final static Property GoodsCode = new Property(16, String.class, "GoodsCode", false, "GOODS_CODE");
        public final static Property GoodsID = new Property(17, Long.class, "GoodsID", false, "GOODS_ID");
        public final static Property GoodsName = new Property(18, String.class, "GoodsName", false, "GOODS_NAME");
        public final static Property IsLargess = new Property(19, Integer.class, "IsLargess", false, "IS_LARGESS");
        public final static Property OrigPrice = new Property(20, Double.class, "OrigPrice", false, "ORIG_PRICE");
        public final static Property OrigTaxPrice = new Property(21, Double.class, "OrigTaxPrice", false, "ORIG_TAX_PRICE");
        public final static Property TaxPrice = new Property(22, Double.class, "TaxPrice", false, "TAX_PRICE");
        public final static Property Price = new Property(23, Double.class, "Price", false, "PRICE");
        public final static Property Quantity = new Property(24, Double.class, "Quantity", false, "QUANTITY");
        public final static Property ReferBillCode = new Property(25, String.class, "ReferBillCode", false, "REFER_BILL_CODE");
        public final static Property ReferBillID = new Property(26, Long.class, "ReferBillID", false, "REFER_BILL_ID");
        public final static Property ReferBillType = new Property(27, String.class, "ReferBillType", false, "REFER_BILL_TYPE");
        public final static Property ReferCount = new Property(28, Integer.class, "ReferCount", false, "REFER_COUNT");
        public final static Property ReferItemNo = new Property(29, Integer.class, "ReferItemNo", false, "REFER_ITEM_NO");
        public final static Property ReferQty = new Property(30, Double.class, "ReferQty", false, "REFER_QTY");
        public final static Property Remark = new Property(31, String.class, "Remark", false, "REMARK");
        public final static Property ShortName = new Property(32, String.class, "ShortName", false, "SHORT_NAME");
        public final static Property Specs = new Property(33, String.class, "Specs", false, "SPECS");
        public final static Property StoreID = new Property(34, Long.class, "StoreID", false, "STORE_ID");
        public final static Property TaxAmt = new Property(35, Double.class, "TaxAmt", false, "TAX_AMT");
        public final static Property TaxRate = new Property(36, Double.class, "TaxRate", false, "TAX_RATE");
        public final static Property UnitID = new Property(37, Long.class, "UnitID", false, "UNIT_ID");
        public final static Property UnitName = new Property(38, String.class, "UnitName", false, "UNIT_NAME");
        public final static Property UnitPrice = new Property(39, Double.class, "UnitPrice", false, "UNIT_PRICE");
        public final static Property UnitQuantity = new Property(40, Double.class, "UnitQuantity", false, "UNIT_QUANTITY");
        public final static Property UnitRate = new Property(41, Double.class, "UnitRate", false, "UNIT_RATE");
        public final static Property UserDef1 = new Property(42, String.class, "UserDef1", false, "USER_DEF1");
        public final static Property UserDef2 = new Property(43, String.class, "UserDef2", false, "USER_DEF2");
        public final static Property UserDef3 = new Property(44, String.class, "UserDef3", false, "USER_DEF3");
        public final static Property UserDef4 = new Property(45, String.class, "UserDef4", false, "USER_DEF4");
        public final static Property UserDef5 = new Property(46, String.class, "UserDef5", false, "USER_DEF5");
    }

}
