package com.twisty.superclient.bean;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SALES_ORDER_MASTER_DATA.
 */
public class SalesOrderMasterData implements java.io.Serializable {

    private Long id;
    private Long BillID;
    private Integer BillState;
    private String BillStateName;
    private Double Amount;
    private String BillCode;
    private String BillDate;
    private String Billto;
    private String CheckorCode;
    private Long CheckorID;
    private String CheckorName;
    private String CloseReason;
    private Integer Closed;
    private String ContactFax;
    private String ContactPhone;
    private String Contactor;
    private String ContractNo;
    private String DepartmentCode;
    private String DepartmentName;
    private Long DepartmentID;
    private String EmpCode;
    private Long EmpID;
    private String EmpName;
    private String LinkMan;
    private String OpCode;
    private Long OpID;
    private String OpName;
    private Long PaymethodID;
    private String PaymethodName;
    private Double ReferAmt;
    private String Remark;
    private String RevDate;
    private Integer Sflag;
    private Long ShipType;
    private String ShipTypeName;
    private Long Shopid;
    private String TraderCode;
    private Long TraderId;
    private String TraderName;
    private String UpdateTime;
    private String UserDef1;
    private String UserDef2;
    private String UserDef3;
    private String UserDef4;
    private String UserDef5;
    private String ValidDate;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient SalesOrderMasterDataDao myDao;

    private List<SalesOrderDetail1Data> salesOrderDetail1DataList;

    public SalesOrderMasterData() {
    }

    public SalesOrderMasterData(Long id) {
        this.id = id;
    }

    public SalesOrderMasterData(Long id, Long BillID, Integer BillState, String BillStateName, Double Amount, String BillCode, String BillDate, String Billto, String CheckorCode, Long CheckorID, String CheckorName, String CloseReason, Integer Closed, String ContactFax, String ContactPhone, String Contactor, String ContractNo, String DepartmentCode, String DepartmentName, Long DepartmentID, String EmpCode, Long EmpID, String EmpName, String LinkMan, String OpCode, Long OpID, String OpName, Long PaymethodID, String PaymethodName, Double ReferAmt, String Remark, String RevDate, Integer Sflag, Long ShipType, String ShipTypeName, Long Shopid, String TraderCode, Long TraderId, String TraderName, String UpdateTime, String UserDef1, String UserDef2, String UserDef3, String UserDef4, String UserDef5, String ValidDate) {
        this.id = id;
        this.BillID = BillID;
        this.BillState = BillState;
        this.BillStateName = BillStateName;
        this.Amount = Amount;
        this.BillCode = BillCode;
        this.BillDate = BillDate;
        this.Billto = Billto;
        this.CheckorCode = CheckorCode;
        this.CheckorID = CheckorID;
        this.CheckorName = CheckorName;
        this.CloseReason = CloseReason;
        this.Closed = Closed;
        this.ContactFax = ContactFax;
        this.ContactPhone = ContactPhone;
        this.Contactor = Contactor;
        this.ContractNo = ContractNo;
        this.DepartmentCode = DepartmentCode;
        this.DepartmentName = DepartmentName;
        this.DepartmentID = DepartmentID;
        this.EmpCode = EmpCode;
        this.EmpID = EmpID;
        this.EmpName = EmpName;
        this.LinkMan = LinkMan;
        this.OpCode = OpCode;
        this.OpID = OpID;
        this.OpName = OpName;
        this.PaymethodID = PaymethodID;
        this.PaymethodName = PaymethodName;
        this.ReferAmt = ReferAmt;
        this.Remark = Remark;
        this.RevDate = RevDate;
        this.Sflag = Sflag;
        this.ShipType = ShipType;
        this.ShipTypeName = ShipTypeName;
        this.Shopid = Shopid;
        this.TraderCode = TraderCode;
        this.TraderId = TraderId;
        this.TraderName = TraderName;
        this.UpdateTime = UpdateTime;
        this.UserDef1 = UserDef1;
        this.UserDef2 = UserDef2;
        this.UserDef3 = UserDef3;
        this.UserDef4 = UserDef4;
        this.UserDef5 = UserDef5;
        this.ValidDate = ValidDate;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSalesOrderMasterDataDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBillID() {
        return BillID;
    }

    public void setBillID(Long BillID) {
        this.BillID = BillID;
    }

    public Integer getBillState() {
        return BillState;
    }

    public void setBillState(Integer BillState) {
        this.BillState = BillState;
    }

    public String getBillStateName() {
        return BillStateName;
    }

    public void setBillStateName(String BillStateName) {
        this.BillStateName = BillStateName;
    }

    public Double getAmount() {
        return Amount;
    }

    public void setAmount(Double Amount) {
        this.Amount = Amount;
    }

    public String getBillCode() {
        return BillCode;
    }

    public void setBillCode(String BillCode) {
        this.BillCode = BillCode;
    }

    public String getBillDate() {
        return BillDate;
    }

    public void setBillDate(String BillDate) {
        this.BillDate = BillDate;
    }

    public String getBillto() {
        return Billto;
    }

    public void setBillto(String Billto) {
        this.Billto = Billto;
    }

    public String getCheckorCode() {
        return CheckorCode;
    }

    public void setCheckorCode(String CheckorCode) {
        this.CheckorCode = CheckorCode;
    }

    public Long getCheckorID() {
        return CheckorID;
    }

    public void setCheckorID(Long CheckorID) {
        this.CheckorID = CheckorID;
    }

    public String getCheckorName() {
        return CheckorName;
    }

    public void setCheckorName(String CheckorName) {
        this.CheckorName = CheckorName;
    }

    public String getCloseReason() {
        return CloseReason;
    }

    public void setCloseReason(String CloseReason) {
        this.CloseReason = CloseReason;
    }

    public Integer getClosed() {
        return Closed;
    }

    public void setClosed(Integer Closed) {
        this.Closed = Closed;
    }

    public String getContactFax() {
        return ContactFax;
    }

    public void setContactFax(String ContactFax) {
        this.ContactFax = ContactFax;
    }

    public String getContactPhone() {
        return ContactPhone;
    }

    public void setContactPhone(String ContactPhone) {
        this.ContactPhone = ContactPhone;
    }

    public String getContactor() {
        return Contactor;
    }

    public void setContactor(String Contactor) {
        this.Contactor = Contactor;
    }

    public String getContractNo() {
        return ContractNo;
    }

    public void setContractNo(String ContractNo) {
        this.ContractNo = ContractNo;
    }

    public String getDepartmentCode() {
        return DepartmentCode;
    }

    public void setDepartmentCode(String DepartmentCode) {
        this.DepartmentCode = DepartmentCode;
    }

    public String getDepartmentName() {
        return DepartmentName;
    }

    public void setDepartmentName(String DepartmentName) {
        this.DepartmentName = DepartmentName;
    }

    public Long getDepartmentID() {
        return DepartmentID;
    }

    public void setDepartmentID(Long DepartmentID) {
        this.DepartmentID = DepartmentID;
    }

    public String getEmpCode() {
        return EmpCode;
    }

    public void setEmpCode(String EmpCode) {
        this.EmpCode = EmpCode;
    }

    public Long getEmpID() {
        return EmpID;
    }

    public void setEmpID(Long EmpID) {
        this.EmpID = EmpID;
    }

    public String getEmpName() {
        return EmpName;
    }

    public void setEmpName(String EmpName) {
        this.EmpName = EmpName;
    }

    public String getLinkMan() {
        return LinkMan;
    }

    public void setLinkMan(String LinkMan) {
        this.LinkMan = LinkMan;
    }

    public String getOpCode() {
        return OpCode;
    }

    public void setOpCode(String OpCode) {
        this.OpCode = OpCode;
    }

    public Long getOpID() {
        return OpID;
    }

    public void setOpID(Long OpID) {
        this.OpID = OpID;
    }

    public String getOpName() {
        return OpName;
    }

    public void setOpName(String OpName) {
        this.OpName = OpName;
    }

    public Long getPaymethodID() {
        return PaymethodID;
    }

    public void setPaymethodID(Long PaymethodID) {
        this.PaymethodID = PaymethodID;
    }

    public String getPaymethodName() {
        return PaymethodName;
    }

    public void setPaymethodName(String PaymethodName) {
        this.PaymethodName = PaymethodName;
    }

    public Double getReferAmt() {
        return ReferAmt;
    }

    public void setReferAmt(Double ReferAmt) {
        this.ReferAmt = ReferAmt;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getRevDate() {
        return RevDate;
    }

    public void setRevDate(String RevDate) {
        this.RevDate = RevDate;
    }

    public Integer getSflag() {
        return Sflag;
    }

    public void setSflag(Integer Sflag) {
        this.Sflag = Sflag;
    }

    public Long getShipType() {
        return ShipType;
    }

    public void setShipType(Long ShipType) {
        this.ShipType = ShipType;
    }

    public String getShipTypeName() {
        return ShipTypeName;
    }

    public void setShipTypeName(String ShipTypeName) {
        this.ShipTypeName = ShipTypeName;
    }

    public Long getShopid() {
        return Shopid;
    }

    public void setShopid(Long Shopid) {
        this.Shopid = Shopid;
    }

    public String getTraderCode() {
        return TraderCode;
    }

    public void setTraderCode(String TraderCode) {
        this.TraderCode = TraderCode;
    }

    public Long getTraderId() {
        return TraderId;
    }

    public void setTraderId(Long TraderId) {
        this.TraderId = TraderId;
    }

    public String getTraderName() {
        return TraderName;
    }

    public void setTraderName(String TraderName) {
        this.TraderName = TraderName;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUserDef1() {
        return UserDef1;
    }

    public void setUserDef1(String UserDef1) {
        this.UserDef1 = UserDef1;
    }

    public String getUserDef2() {
        return UserDef2;
    }

    public void setUserDef2(String UserDef2) {
        this.UserDef2 = UserDef2;
    }

    public String getUserDef3() {
        return UserDef3;
    }

    public void setUserDef3(String UserDef3) {
        this.UserDef3 = UserDef3;
    }

    public String getUserDef4() {
        return UserDef4;
    }

    public void setUserDef4(String UserDef4) {
        this.UserDef4 = UserDef4;
    }

    public String getUserDef5() {
        return UserDef5;
    }

    public void setUserDef5(String UserDef5) {
        this.UserDef5 = UserDef5;
    }

    public String getValidDate() {
        return ValidDate;
    }

    public void setValidDate(String ValidDate) {
        this.ValidDate = ValidDate;
    }

    /**
     * To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity.
     */
    public List<SalesOrderDetail1Data> getSalesOrderDetail1DataList() {
        if (salesOrderDetail1DataList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SalesOrderDetail1DataDao targetDao = daoSession.getSalesOrderDetail1DataDao();
            List<SalesOrderDetail1Data> salesOrderDetail1DataListNew = targetDao._querySalesOrderMasterData_SalesOrderDetail1DataList(id);
            synchronized (this) {
                if (salesOrderDetail1DataList == null) {
                    salesOrderDetail1DataList = salesOrderDetail1DataListNew;
                }
            }
        }
        return salesOrderDetail1DataList;
    }

    /**
     * Resets a to-many relationship, making the next get call to query for a fresh result.
     */
    public synchronized void resetSalesOrderDetail1DataList() {
        salesOrderDetail1DataList = null;
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

}
