package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STOCK_CHECK_DETAIL1_DATA.
 */
public class StockCheckDetail1Data implements java.io.Serializable {

    private Long BillID;
    private Long GoodsID;
    private Long UnitID;
    private Integer ItemNo;
    private Integer ReferCount;
    private Double APrice;
    private Double UnitPrice;
    private Double UnitRate;
    private Double UnitQuantity;
    private Double UnitRealQty;
    private Double AccQty;
    private Double Amount;
    private Double IOQty;
    private Double Price;
    private Double Quantity;
    private String GoodsCode;
    private String GoodsName;
    private String Remark;
    private String Specs;
    private String UnitName;
    private String UserDef1;
    private String UserDef2;
    private String UserDef3;
    private String UserDef4;
    private String UserDef5;

    public StockCheckDetail1Data() {
    }

    public StockCheckDetail1Data(Long BillID, Long GoodsID, Long UnitID, Integer ItemNo, Integer ReferCount, Double APrice, Double UnitPrice, Double UnitRate, Double UnitQuantity, Double UnitRealQty, Double AccQty, Double Amount, Double IOQty, Double Price, Double Quantity, String GoodsCode, String GoodsName, String Remark, String Specs, String UnitName, String UserDef1, String UserDef2, String UserDef3, String UserDef4, String UserDef5) {
        this.BillID = BillID;
        this.GoodsID = GoodsID;
        this.UnitID = UnitID;
        this.ItemNo = ItemNo;
        this.ReferCount = ReferCount;
        this.APrice = APrice;
        this.UnitPrice = UnitPrice;
        this.UnitRate = UnitRate;
        this.UnitQuantity = UnitQuantity;
        this.UnitRealQty = UnitRealQty;
        this.AccQty = AccQty;
        this.Amount = Amount;
        this.IOQty = IOQty;
        this.Price = Price;
        this.Quantity = Quantity;
        this.GoodsCode = GoodsCode;
        this.GoodsName = GoodsName;
        this.Remark = Remark;
        this.Specs = Specs;
        this.UnitName = UnitName;
        this.UserDef1 = UserDef1;
        this.UserDef2 = UserDef2;
        this.UserDef3 = UserDef3;
        this.UserDef4 = UserDef4;
        this.UserDef5 = UserDef5;
    }

    public Long getBillID() {
        return BillID;
    }

    public void setBillID(Long BillID) {
        this.BillID = BillID;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public Long getUnitID() {
        return UnitID;
    }

    public void setUnitID(Long UnitID) {
        this.UnitID = UnitID;
    }

    public Integer getItemNo() {
        return ItemNo;
    }

    public void setItemNo(Integer ItemNo) {
        this.ItemNo = ItemNo;
    }

    public Integer getReferCount() {
        return ReferCount;
    }

    public void setReferCount(Integer ReferCount) {
        this.ReferCount = ReferCount;
    }

    public Double getAPrice() {
        return APrice;
    }

    public void setAPrice(Double APrice) {
        this.APrice = APrice;
    }

    public Double getUnitPrice() {
        return UnitPrice;
    }

    public void setUnitPrice(Double UnitPrice) {
        this.UnitPrice = UnitPrice;
    }

    public Double getUnitRate() {
        return UnitRate;
    }

    public void setUnitRate(Double UnitRate) {
        this.UnitRate = UnitRate;
    }

    public Double getUnitQuantity() {
        return UnitQuantity;
    }

    public void setUnitQuantity(Double UnitQuantity) {
        this.UnitQuantity = UnitQuantity;
    }

    public Double getUnitRealQty() {
        return UnitRealQty;
    }

    public void setUnitRealQty(Double UnitRealQty) {
        this.UnitRealQty = UnitRealQty;
    }

    public Double getAccQty() {
        return AccQty;
    }

    public void setAccQty(Double AccQty) {
        this.AccQty = AccQty;
    }

    public Double getAmount() {
        return Amount;
    }

    public void setAmount(Double Amount) {
        this.Amount = Amount;
    }

    public Double getIOQty() {
        return IOQty;
    }

    public void setIOQty(Double IOQty) {
        this.IOQty = IOQty;
    }

    public Double getPrice() {
        return Price;
    }

    public void setPrice(Double Price) {
        this.Price = Price;
    }

    public Double getQuantity() {
        return Quantity;
    }

    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    public String getGoodsCode() {
        return GoodsCode;
    }

    public void setGoodsCode(String GoodsCode) {
        this.GoodsCode = GoodsCode;
    }

    public String getGoodsName() {
        return GoodsName;
    }

    public void setGoodsName(String GoodsName) {
        this.GoodsName = GoodsName;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getSpecs() {
        return Specs;
    }

    public void setSpecs(String Specs) {
        this.Specs = Specs;
    }

    public String getUnitName() {
        return UnitName;
    }

    public void setUnitName(String UnitName) {
        this.UnitName = UnitName;
    }

    public String getUserDef1() {
        return UserDef1;
    }

    public void setUserDef1(String UserDef1) {
        this.UserDef1 = UserDef1;
    }

    public String getUserDef2() {
        return UserDef2;
    }

    public void setUserDef2(String UserDef2) {
        this.UserDef2 = UserDef2;
    }

    public String getUserDef3() {
        return UserDef3;
    }

    public void setUserDef3(String UserDef3) {
        this.UserDef3 = UserDef3;
    }

    public String getUserDef4() {
        return UserDef4;
    }

    public void setUserDef4(String UserDef4) {
        this.UserDef4 = UserDef4;
    }

    public String getUserDef5() {
        return UserDef5;
    }

    public void setUserDef5(String UserDef5) {
        this.UserDef5 = UserDef5;
    }

}
