package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SYS_PARAM.
 */
public class SysParam implements java.io.Serializable {

    private Long ParamID;
    private String ParamName;
    private String DataValue;
    private String Content;
    private String LCode;

    public SysParam() {
    }

    public SysParam(Long ParamID, String ParamName, String DataValue, String Content, String LCode) {
        this.ParamID = ParamID;
        this.ParamName = ParamName;
        this.DataValue = DataValue;
        this.Content = Content;
        this.LCode = LCode;
    }

    public Long getParamID() {
        return ParamID;
    }

    public void setParamID(Long ParamID) {
        this.ParamID = ParamID;
    }

    public String getParamName() {
        return ParamName;
    }

    public void setParamName(String ParamName) {
        this.ParamName = ParamName;
    }

    public String getDataValue() {
        return DataValue;
    }

    public void setDataValue(String DataValue) {
        this.DataValue = DataValue;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public String getLCode() {
        return LCode;
    }

    public void setLCode(String LCode) {
        this.LCode = LCode;
    }

}
