package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRADER.
 */
public class Trader implements java.io.Serializable {

    private Long TraderID;
    private String TraderCode;
    private String TraderName;
    private String FullName;
    private Boolean IsClient;
    private Boolean IsVendor;
    private Long TraderTypeID;
    private Long AreaID;
    private String Lev;
    private Long EmpID;
    private Long DepartmentID;
    private Long Legalrep;
    private Long Contactor;
    private String Phone;
    private String Tel1;
    private String Tel2;
    private String Fax;
    private String Zip;
    private String Address;
    private String ShipTo;
    private String EMail;
    private String Url;
    private String Bank;
    private String BankAccno;
    private String TaxNo;
    private String CreditDay;
    private String Credit;
    private Boolean Closed;
    private Boolean AccTrader;

    public Trader() {
    }

    public Trader(Long TraderID, String TraderCode, String TraderName, String FullName, Boolean IsClient, Boolean IsVendor, Long TraderTypeID, Long AreaID, String Lev, Long EmpID, Long DepartmentID, Long Legalrep, Long Contactor, String Phone, String Tel1, String Tel2, String Fax, String Zip, String Address, String ShipTo, String EMail, String Url, String Bank, String BankAccno, String TaxNo, String CreditDay, String Credit, Boolean Closed, Boolean AccTrader) {
        this.TraderID = TraderID;
        this.TraderCode = TraderCode;
        this.TraderName = TraderName;
        this.FullName = FullName;
        this.IsClient = IsClient;
        this.IsVendor = IsVendor;
        this.TraderTypeID = TraderTypeID;
        this.AreaID = AreaID;
        this.Lev = Lev;
        this.EmpID = EmpID;
        this.DepartmentID = DepartmentID;
        this.Legalrep = Legalrep;
        this.Contactor = Contactor;
        this.Phone = Phone;
        this.Tel1 = Tel1;
        this.Tel2 = Tel2;
        this.Fax = Fax;
        this.Zip = Zip;
        this.Address = Address;
        this.ShipTo = ShipTo;
        this.EMail = EMail;
        this.Url = Url;
        this.Bank = Bank;
        this.BankAccno = BankAccno;
        this.TaxNo = TaxNo;
        this.CreditDay = CreditDay;
        this.Credit = Credit;
        this.Closed = Closed;
        this.AccTrader = AccTrader;
    }

    public Long getTraderID() {
        return TraderID;
    }

    public void setTraderID(Long TraderID) {
        this.TraderID = TraderID;
    }

    public String getTraderCode() {
        return TraderCode;
    }

    public void setTraderCode(String TraderCode) {
        this.TraderCode = TraderCode;
    }

    public String getTraderName() {
        return TraderName;
    }

    public void setTraderName(String TraderName) {
        this.TraderName = TraderName;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public Boolean getIsClient() {
        return IsClient;
    }

    public void setIsClient(Boolean IsClient) {
        this.IsClient = IsClient;
    }

    public Boolean getIsVendor() {
        return IsVendor;
    }

    public void setIsVendor(Boolean IsVendor) {
        this.IsVendor = IsVendor;
    }

    public Long getTraderTypeID() {
        return TraderTypeID;
    }

    public void setTraderTypeID(Long TraderTypeID) {
        this.TraderTypeID = TraderTypeID;
    }

    public Long getAreaID() {
        return AreaID;
    }

    public void setAreaID(Long AreaID) {
        this.AreaID = AreaID;
    }

    public String getLev() {
        return Lev;
    }

    public void setLev(String Lev) {
        this.Lev = Lev;
    }

    public Long getEmpID() {
        return EmpID;
    }

    public void setEmpID(Long EmpID) {
        this.EmpID = EmpID;
    }

    public Long getDepartmentID() {
        return DepartmentID;
    }

    public void setDepartmentID(Long DepartmentID) {
        this.DepartmentID = DepartmentID;
    }

    public Long getLegalrep() {
        return Legalrep;
    }

    public void setLegalrep(Long Legalrep) {
        this.Legalrep = Legalrep;
    }

    public Long getContactor() {
        return Contactor;
    }

    public void setContactor(Long Contactor) {
        this.Contactor = Contactor;
    }

    public String getPhone() {
        return Phone;
    }

    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public String getTel1() {
        return Tel1;
    }

    public void setTel1(String Tel1) {
        this.Tel1 = Tel1;
    }

    public String getTel2() {
        return Tel2;
    }

    public void setTel2(String Tel2) {
        this.Tel2 = Tel2;
    }

    public String getFax() {
        return Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    public String getZip() {
        return Zip;
    }

    public void setZip(String Zip) {
        this.Zip = Zip;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getShipTo() {
        return ShipTo;
    }

    public void setShipTo(String ShipTo) {
        this.ShipTo = ShipTo;
    }

    public String getEMail() {
        return EMail;
    }

    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    public String getUrl() {
        return Url;
    }

    public void setUrl(String Url) {
        this.Url = Url;
    }

    public String getBank() {
        return Bank;
    }

    public void setBank(String Bank) {
        this.Bank = Bank;
    }

    public String getBankAccno() {
        return BankAccno;
    }

    public void setBankAccno(String BankAccno) {
        this.BankAccno = BankAccno;
    }

    public String getTaxNo() {
        return TaxNo;
    }

    public void setTaxNo(String TaxNo) {
        this.TaxNo = TaxNo;
    }

    public String getCreditDay() {
        return CreditDay;
    }

    public void setCreditDay(String CreditDay) {
        this.CreditDay = CreditDay;
    }

    public String getCredit() {
        return Credit;
    }

    public void setCredit(String Credit) {
        this.Credit = Credit;
    }

    public Boolean getClosed() {
        return Closed;
    }

    public void setClosed(Boolean Closed) {
        this.Closed = Closed;
    }

    public Boolean getAccTrader() {
        return AccTrader;
    }

    public void setAccTrader(Boolean AccTrader) {
        this.AccTrader = AccTrader;
    }

}
