package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRADE_TYPE.
 */
public class TradeType implements java.io.Serializable {

    private Long TradeTypeID;
    private String TradeTypeCode;
    private String TradeTypeName;
    private String LCode;
    private Long ParentID;

    public TradeType() {
    }

    public TradeType(Long TradeTypeID, String TradeTypeCode, String TradeTypeName, String LCode, Long ParentID) {
        this.TradeTypeID = TradeTypeID;
        this.TradeTypeCode = TradeTypeCode;
        this.TradeTypeName = TradeTypeName;
        this.LCode = LCode;
        this.ParentID = ParentID;
    }

    public Long getTradeTypeID() {
        return TradeTypeID;
    }

    public void setTradeTypeID(Long TradeTypeID) {
        this.TradeTypeID = TradeTypeID;
    }

    public String getTradeTypeCode() {
        return TradeTypeCode;
    }

    public void setTradeTypeCode(String TradeTypeCode) {
        this.TradeTypeCode = TradeTypeCode;
    }

    public String getTradeTypeName() {
        return TradeTypeName;
    }

    public void setTradeTypeName(String TradeTypeName) {
        this.TradeTypeName = TradeTypeName;
    }

    public String getLCode() {
        return LCode;
    }

    public void setLCode(String LCode) {
        this.LCode = LCode;
    }

    public Long getParentID() {
        return ParentID;
    }

    public void setParentID(Long ParentID) {
        this.ParentID = ParentID;
    }

}
