package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRANSFER_DETAIL1_DATA.
 */
public class TransferDetail1Data implements java.io.Serializable {

    private Long BillID;
    private Long GoodsID;
    private Long ReferBillID;
    private Long UnitID;
    private Integer ItemNo;
    private Integer ReferCount;
    private Integer ReferItemNo;
    private Integer ReferBillType;
    private Double APrice;
    private Double BeforePrice;
    private Double Amount;
    private Double UnitPrice;
    private Double Price;
    private Double Quantity;
    private Double IOQty;
    private Double OIQty;
    private Double UnitQuantity;
    private Double UnitRate;
    private String BarCode;
    private String GoodsCode;
    private String ReferBillCode;
    private String Remark;
    private String GoodsName;
    private String ShortName;
    private String Specs;
    private String UnitName;
    private String UserDef1;
    private String UserDef2;
    private String UserDef3;
    private String UserDef4;
    private String UserDef5;

    public TransferDetail1Data() {
    }

    public TransferDetail1Data(Long BillID, Long GoodsID, Long ReferBillID, Long UnitID, Integer ItemNo, Integer ReferCount, Integer ReferItemNo, Integer ReferBillType, Double APrice, Double BeforePrice, Double Amount, Double UnitPrice, Double Price, Double Quantity, Double IOQty, Double OIQty, Double UnitQuantity, Double UnitRate, String BarCode, String GoodsCode, String ReferBillCode, String Remark, String GoodsName, String ShortName, String Specs, String UnitName, String UserDef1, String UserDef2, String UserDef3, String UserDef4, String UserDef5) {
        this.BillID = BillID;
        this.GoodsID = GoodsID;
        this.ReferBillID = ReferBillID;
        this.UnitID = UnitID;
        this.ItemNo = ItemNo;
        this.ReferCount = ReferCount;
        this.ReferItemNo = ReferItemNo;
        this.ReferBillType = ReferBillType;
        this.APrice = APrice;
        this.BeforePrice = BeforePrice;
        this.Amount = Amount;
        this.UnitPrice = UnitPrice;
        this.Price = Price;
        this.Quantity = Quantity;
        this.IOQty = IOQty;
        this.OIQty = OIQty;
        this.UnitQuantity = UnitQuantity;
        this.UnitRate = UnitRate;
        this.BarCode = BarCode;
        this.GoodsCode = GoodsCode;
        this.ReferBillCode = ReferBillCode;
        this.Remark = Remark;
        this.GoodsName = GoodsName;
        this.ShortName = ShortName;
        this.Specs = Specs;
        this.UnitName = UnitName;
        this.UserDef1 = UserDef1;
        this.UserDef2 = UserDef2;
        this.UserDef3 = UserDef3;
        this.UserDef4 = UserDef4;
        this.UserDef5 = UserDef5;
    }

    public Long getBillID() {
        return BillID;
    }

    public void setBillID(Long BillID) {
        this.BillID = BillID;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public Long getReferBillID() {
        return ReferBillID;
    }

    public void setReferBillID(Long ReferBillID) {
        this.ReferBillID = ReferBillID;
    }

    public Long getUnitID() {
        return UnitID;
    }

    public void setUnitID(Long UnitID) {
        this.UnitID = UnitID;
    }

    public Integer getItemNo() {
        return ItemNo;
    }

    public void setItemNo(Integer ItemNo) {
        this.ItemNo = ItemNo;
    }

    public Integer getReferCount() {
        return ReferCount;
    }

    public void setReferCount(Integer ReferCount) {
        this.ReferCount = ReferCount;
    }

    public Integer getReferItemNo() {
        return ReferItemNo;
    }

    public void setReferItemNo(Integer ReferItemNo) {
        this.ReferItemNo = ReferItemNo;
    }

    public Integer getReferBillType() {
        return ReferBillType;
    }

    public void setReferBillType(Integer ReferBillType) {
        this.ReferBillType = ReferBillType;
    }

    public Double getAPrice() {
        return APrice;
    }

    public void setAPrice(Double APrice) {
        this.APrice = APrice;
    }

    public Double getBeforePrice() {
        return BeforePrice;
    }

    public void setBeforePrice(Double BeforePrice) {
        this.BeforePrice = BeforePrice;
    }

    public Double getAmount() {
        return Amount;
    }

    public void setAmount(Double Amount) {
        this.Amount = Amount;
    }

    public Double getUnitPrice() {
        return UnitPrice;
    }

    public void setUnitPrice(Double UnitPrice) {
        this.UnitPrice = UnitPrice;
    }

    public Double getPrice() {
        return Price;
    }

    public void setPrice(Double Price) {
        this.Price = Price;
    }

    public Double getQuantity() {
        return Quantity;
    }

    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    public Double getIOQty() {
        return IOQty;
    }

    public void setIOQty(Double IOQty) {
        this.IOQty = IOQty;
    }

    public Double getOIQty() {
        return OIQty;
    }

    public void setOIQty(Double OIQty) {
        this.OIQty = OIQty;
    }

    public Double getUnitQuantity() {
        return UnitQuantity;
    }

    public void setUnitQuantity(Double UnitQuantity) {
        this.UnitQuantity = UnitQuantity;
    }

    public Double getUnitRate() {
        return UnitRate;
    }

    public void setUnitRate(Double UnitRate) {
        this.UnitRate = UnitRate;
    }

    public String getBarCode() {
        return BarCode;
    }

    public void setBarCode(String BarCode) {
        this.BarCode = BarCode;
    }

    public String getGoodsCode() {
        return GoodsCode;
    }

    public void setGoodsCode(String GoodsCode) {
        this.GoodsCode = GoodsCode;
    }

    public String getReferBillCode() {
        return ReferBillCode;
    }

    public void setReferBillCode(String ReferBillCode) {
        this.ReferBillCode = ReferBillCode;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getGoodsName() {
        return GoodsName;
    }

    public void setGoodsName(String GoodsName) {
        this.GoodsName = GoodsName;
    }

    public String getShortName() {
        return ShortName;
    }

    public void setShortName(String ShortName) {
        this.ShortName = ShortName;
    }

    public String getSpecs() {
        return Specs;
    }

    public void setSpecs(String Specs) {
        this.Specs = Specs;
    }

    public String getUnitName() {
        return UnitName;
    }

    public void setUnitName(String UnitName) {
        this.UnitName = UnitName;
    }

    public String getUserDef1() {
        return UserDef1;
    }

    public void setUserDef1(String UserDef1) {
        this.UserDef1 = UserDef1;
    }

    public String getUserDef2() {
        return UserDef2;
    }

    public void setUserDef2(String UserDef2) {
        this.UserDef2 = UserDef2;
    }

    public String getUserDef3() {
        return UserDef3;
    }

    public void setUserDef3(String UserDef3) {
        this.UserDef3 = UserDef3;
    }

    public String getUserDef4() {
        return UserDef4;
    }

    public void setUserDef4(String UserDef4) {
        this.UserDef4 = UserDef4;
    }

    public String getUserDef5() {
        return UserDef5;
    }

    public void setUserDef5(String UserDef5) {
        this.UserDef5 = UserDef5;
    }

}
