package com.twisty.superclient.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table UNIT.
 */
public class Unit implements java.io.Serializable {

    private Long UnitID;
    private Long GoodsID;
    private String UnitName;
    private String BarCode;
    private Double Rate;
    private Integer IsBase;
    private Double SPrice;
    private Double PPrice;
    private Double HighPrice;
    private Double LowPrice;
    private Double VipPrice;
    private Double LPrice1;
    private Double LPrice2;
    private Double LPrice3;
    private Double LPrice4;
    private Double LPrice5;
    private Integer IsSale;
    private Integer IsPurchase;
    private Integer IsStore;

    public Unit() {
    }

    public Unit(Long UnitID, Long GoodsID, String UnitName, String BarCode, Double Rate, Integer IsBase, Double SPrice, Double PPrice, Double HighPrice, Double LowPrice, Double VipPrice, Double LPrice1, Double LPrice2, Double LPrice3, Double LPrice4, Double LPrice5, Integer IsSale, Integer IsPurchase, Integer IsStore) {
        this.UnitID = UnitID;
        this.GoodsID = GoodsID;
        this.UnitName = UnitName;
        this.BarCode = BarCode;
        this.Rate = Rate;
        this.IsBase = IsBase;
        this.SPrice = SPrice;
        this.PPrice = PPrice;
        this.HighPrice = HighPrice;
        this.LowPrice = LowPrice;
        this.VipPrice = VipPrice;
        this.LPrice1 = LPrice1;
        this.LPrice2 = LPrice2;
        this.LPrice3 = LPrice3;
        this.LPrice4 = LPrice4;
        this.LPrice5 = LPrice5;
        this.IsSale = IsSale;
        this.IsPurchase = IsPurchase;
        this.IsStore = IsStore;
    }

    public Long getUnitID() {
        return UnitID;
    }

    public void setUnitID(Long UnitID) {
        this.UnitID = UnitID;
    }

    public Long getGoodsID() {
        return GoodsID;
    }

    public void setGoodsID(Long GoodsID) {
        this.GoodsID = GoodsID;
    }

    public String getUnitName() {
        return UnitName;
    }

    public void setUnitName(String UnitName) {
        this.UnitName = UnitName;
    }

    public String getBarCode() {
        return BarCode;
    }

    public void setBarCode(String BarCode) {
        this.BarCode = BarCode;
    }

    public Double getRate() {
        return Rate;
    }

    public void setRate(Double Rate) {
        this.Rate = Rate;
    }

    public Integer getIsBase() {
        return IsBase;
    }

    public void setIsBase(Integer IsBase) {
        this.IsBase = IsBase;
    }

    public Double getSPrice() {
        return SPrice;
    }

    public void setSPrice(Double SPrice) {
        this.SPrice = SPrice;
    }

    public Double getPPrice() {
        return PPrice;
    }

    public void setPPrice(Double PPrice) {
        this.PPrice = PPrice;
    }

    public Double getHighPrice() {
        return HighPrice;
    }

    public void setHighPrice(Double HighPrice) {
        this.HighPrice = HighPrice;
    }

    public Double getLowPrice() {
        return LowPrice;
    }

    public void setLowPrice(Double LowPrice) {
        this.LowPrice = LowPrice;
    }

    public Double getVipPrice() {
        return VipPrice;
    }

    public void setVipPrice(Double VipPrice) {
        this.VipPrice = VipPrice;
    }

    public Double getLPrice1() {
        return LPrice1;
    }

    public void setLPrice1(Double LPrice1) {
        this.LPrice1 = LPrice1;
    }

    public Double getLPrice2() {
        return LPrice2;
    }

    public void setLPrice2(Double LPrice2) {
        this.LPrice2 = LPrice2;
    }

    public Double getLPrice3() {
        return LPrice3;
    }

    public void setLPrice3(Double LPrice3) {
        this.LPrice3 = LPrice3;
    }

    public Double getLPrice4() {
        return LPrice4;
    }

    public void setLPrice4(Double LPrice4) {
        this.LPrice4 = LPrice4;
    }

    public Double getLPrice5() {
        return LPrice5;
    }

    public void setLPrice5(Double LPrice5) {
        this.LPrice5 = LPrice5;
    }

    public Integer getIsSale() {
        return IsSale;
    }

    public void setIsSale(Integer IsSale) {
        this.IsSale = IsSale;
    }

    public Integer getIsPurchase() {
        return IsPurchase;
    }

    public void setIsPurchase(Integer IsPurchase) {
        this.IsPurchase = IsPurchase;
    }

    public Integer getIsStore() {
        return IsStore;
    }

    public void setIsStore(Integer IsStore) {
        this.IsStore = IsStore;
    }

}
